//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConnectDBSQL.Classes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GokkeeEntities : DbContext
    {
        private static GokkeeEntities _context;
        public GokkeeEntities()
            : base("name=GokkeeEntities")
        {
        }

        public static GokkeeEntities GetGokkee()
        {
            if (_context == null)
                _context = new GokkeeEntities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Group> Group { get; set; }
        public virtual DbSet<Person> Person { get; set; }
    }
}
